---
ID: "ce576e13-5713-434b-9960-162cd839e05c"
Parent: "b79b5166-c106-4f82-a8ca-11cec6032d52"
Template: "b79b5166-c106-4f82-a8ca-11cec6032d52"
Path: "/sitecore/templates/Project/industry-verticals/Pages/DestinationPage/__Standard Values"
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {98E60957-0783-4A9A-85CC-77DAD30E9711}
    {C14B6289-8AC2-439C-9E5B-40DE9F820C3F}
    {B79B5166-C106-4F82-A8CA-11CEC6032D52}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "892f1003-caa5-407d-9862-59cc2e81b519"
- ID: "fd4e2050-186c-4375-8b99-e8a85dd7436e"
  Hint: __Enable item fallback
  Value: 
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20250820T091612Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "56856428-f4ee-4092-9dec-ef5e667fc807"
      Hint: Title
      Value: $name
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "5759f29d-15f1-4edf-9fa4-174c58b1441d"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\neli.kostadinova@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251210T134442Z
