---
ID: "3d8fed01-a6ad-49a8-a6d6-d2f6ed89c07a"
Parent: "a3a58074-c4b7-478b-b0b4-386243e7e48e"
Template: "98e60957-0783-4a9a-85cc-77dad30e9711"
Path: "/sitecore/content/industry-verticals/gridwell/Home/Services"
SharedFields:
- ID: "1fbc6a49-6281-48ee-87e9-a3970b145adb"
  Hint: NavigationFilter
  Value: 
- ID: "25f9b35b-0c2c-4f43-ae2f-1d30eb1f2b6b"
  Hint: ogImage
  Value: |
    <Image src="https://starter-verticals-v2.sitecoresandbox.cloud/api/public/content/31e7d51faa8f4c49be79a5d041f8a857?v=eca564cd" dam-id="kROJ4I3eTbGS_yxwxaHktg" width="200" height="200" alt="lineworker-on-pole.png" dam-content-type="Image" thumbnailsrc="https://starter-verticals-v2.sitecoresandbox.cloud/api/gateway/70196/thumbnail" />
- ID: "ba3f86a2-4a1c-4d78-b63d-91c2779c1b5e"
  Hint: __Sortorder
  Value: 225
- ID: "c7c26117-dbb1-42b2-ab5e-f7223845cca3"
  Hint: __Thumbnail
  Value: |
    <image mediaid="{D12F0232-8249-4DC0-804E-C0B734A5DED8}" />
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "9f21452c-addd-44bd-b242-9591c5f74e7f"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "001dd393-96c5-490b-924a-b0f25cd9efd8"
      Hint: __Lock
      Value: <r />
    - ID: "13fe722e-a8c7-4432-a983-23fb28ffab05"
      Hint: metadataKeywords
      Value: Gridwell services, grid operations, energy market services, power grid coordination, energy reliability
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20260112T110553Z
    - ID: "32c603c2-c858-4138-8fcb-8e18a5ad8240"
      Hint: metadataTitle
      Value: Gridwell Services | Powering Reliable Energy Operations
    - ID: "4e0720e9-9d50-4ddc-87cf-ecd65e8e94c8"
      Hint: NavigationTitle
      Value: Services
    - ID: "4ff91248-33ab-4254-b6f7-2618fd0aebae"
      Hint: Title
      Value: Services
    - ID: "6b43d550-6d5f-46ce-ac84-3d9493c45bc6"
      Hint: metadataDescription
      Value: Gridwell provides critical services that ensure reliable grid operations, transparent market coordination, and clear public communication. These services support households, businesses, and energy partners across Texas.
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "e87ca851-639e-4415-81ff-88f341c59408"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\ranula.gamage@sitecore.com
    - ID: "d3886445-9ee0-46a0-ae5e-8857dd6b395f"
      Hint: pageSummary
      Value: Gridwell’s services support the safe and reliable operation of the power grid through system coordination, market oversight, and public communication. This page outlines how Gridwell works with communities and partners to maintain grid stability and trust.
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260129T105847Z
