---
ID: "0061557b-662a-401b-b6c6-c04beadc359d"
Parent: "c3ac2de7-864d-4ad1-abff-faf7b45ab59c"
Template: "c3ac2de7-864d-4ad1-abff-faf7b45ab59c"
Path: /sitecore/templates/Project/retail/Components/Products/Product Reviews/Product Reviews Folder/__Standard Values
SharedFields:
- ID: "1172f251-dad4-4efb-a329-0c63500e4f1e"
  Hint: __Masters
  Value: |
    {C5F4C503-41FE-486B-A6C7-08E54C80ED68}
    {C3AC2DE7-864D-4AD1-ABFF-FAF7B45AB59C}
- ID: "dbbbeca1-21c7-4906-9dd2-493c1efa59a2"
  Hint: __Shared revision
  Value: "6a02f5b4-f86b-42ca-90b5-e9fc291c90f3"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20120621T071605Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7bea85f5-37e7-4b05-b104-c3008f99a403"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\sanduni.galagoda@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20251015T092311Z
